[project]
name = "prosec-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "docker>=7.1.0",
    "drain3>=0.9.11",
    "fastapi>=0.133.1",
    "pydantic>=2.12.5",
]
